name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x' # Adjust to your project's .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Package
      run: |
        mkdir -p release
        cp -r **/bin/Release/* release/
        cd release
        zip -r release.zip .

    - name: Upload Release Asset
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release/release.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Release Asset
      uses: actions/download-artifact@v2
      with:
        name: release

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
